text_input_ebay = ["Title", "Ebay Title","Description", "Hashtags", "Bought For Price", "Listing Price", "Brand", "Size", "Location"]
INFO_LINES = [
    "#INFO,Version=0.0.2,Template= eBay-draft-listings-template_US,,,,,,,,",
    "#INFO Action and Category ID are required fields. 1) Set Action to Draft 2) Please find the category ID for your listings here: https://pages.ebay.com/sellerinformation/news/categorychanges.html,,,,,,,,,,",
    "\"#INFO After you've successfully uploaded your draft from the Seller Hub Reports tab, complete your drafts to active listings here: https://www.ebay.com/sh/lst/drafts\",,,,,,,,,,",
    "#INFO,,,,,,,,,,",
]

HEADERS = [
    "Action(SiteID=US|Country=US|Currency=USD|Version=1193|CC=UTF-8)",
    "Custom label (SKU)",
    "Category ID",
    "Title",
    "UPC",
    "Price",
    "Quantity",
    "Item photo URL",
    "Condition ID",
    "Description",
    "Format",
    "C:Brand",
    "C:Style",
    "C:Size Type",
    "C:Size",
    "C:Department",
    "C:Color",
    "C:Type",
    "C:Material",
    "C:Neckline",
    "C:Fabric Type",
    "C:Character",
    "C:Theme",
    "C:Features",
    "C:Knit Style",
    "C:Pattern",
    "C:Country of Origin",
    "C:Accents",
    "C:Vintage",
    "C:Performance/Activity",
    "C:Sleeve Length",
    "C:Fit",
    "C:Season",
    "C:Occasion",
]