options = {
    "boots": ["Action(SiteID=US|Country=US|Currency=USD|Version=1193|CC=UTF-8),"
        "Custom label (SKU),"
        "Category ID,"
        "Title,"
        "UPC,"
        "Price,"
        "Quantity,"
        "Item photo URL,"
        "Condition ID,"
        "Description,"
        "Format,"
        "C:Brand, C:US Shoe Size, C:Style, C:Department, C:Color, C:Upper Material, "
        "C:UK Shoe Size, C:AU Shoe Size, C:Pattern, C:Theme, C:Shoe Width, C:Closure, "
        "C:Features, C:EU Shoe Size, C:Vintage"],
    
    "depop": ["Description,"
        "Category,"
        "Price,"
        "Brand,"
        "Condition,"
        "Size,"
        "Color 1,"
        "Color 2,"
        "Source 1,"
        "Source 2,"
        "Age,"
        "Style 1,"
        "Style 2,"
        "Style 3,"
        "Location,"
        "Picture Hero url,"
        "Picture 2 url,"
        "Picture 3 url,"
        "Picture 4 url,"
        "Picture 5 url,"
        "Picture 6 url,"
        "Picture 7 url,"
        "Picture 8 url,"
        "Domestic Shipping price,"
        "International Shipping price"]
}
